-- Adds a PGDBA schema with DEL_JOB_TABLE_LIST (the ILM/partition-retention
-- registry the real internal-network DB has) plus real range-partitioned
-- sample tables at day/month/year granularity, so the local test DB has
-- something for the ILM Partition Retention screen to show end to end.
--
-- Only runs automatically on a FRESH container (gvenzl images run
-- container-entrypoint-initdb.d scripts once, on first init). If the data
-- volume already exists, run this file manually instead, e.g.:
--   docker exec -i oracle-daily-monitoring-test sqlplus -s system/<pw>@FREEPDB1 \
--     < docker/initdb/03_ilm_partition_retention.sql

ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER pgdba IDENTIFIED BY "PgdbaTest_2026!" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE TO pgdba;

CREATE TABLE pgdba.DEL_JOB_TABLE_LIST
(
    TABLE_OWNER         VARCHAR2(30),
    TABLE_NAME          VARCHAR2(30),
    COMMENTS            VARCHAR2(500),
    WORK_GROUP          VARCHAR2(3),
    STD_COLUMN          VARCHAR2(100),
    START_HIGHVALUE     VARCHAR2(83),
    END_HIGHVALUE       VARCHAR2(100),
    DELETE_CYCLE        VARCHAR2(100),
    RANGE_TYPE          VARCHAR2(20),
    PARTITION_YN        VARCHAR2(2),
    PARTITION_TYPE      VARCHAR2(20),
    OGG_SYNC_YN         VARCHAR2(2),
    STATUS              VARCHAR2(10),
    LAST_DEL_JOB_TIME   TIMESTAMP(6),
    STD_DATE            VARCHAR2(100),
    MEMO                VARCHAR2(4000)
);

-- Three real range-partitioned sample tables under SYSTEM (the account the
-- app's local test DBMS entry connects as) — one each at MONTH / DAY / YEAR
-- partition granularity, with a little data so a "SELECT * " on them isn't empty.

-- MONTH granularity: monthly order log, 6 months.
CREATE TABLE system.ORDER_LOG
(
    ORDER_ID    NUMBER NOT NULL,
    ORDER_DATE  DATE NOT NULL,
    CUSTOMER_ID NUMBER,
    AMOUNT      NUMBER(12,2)
)
PARTITION BY RANGE (ORDER_DATE)
(
    PARTITION ORDER_LOG_P202601 VALUES LESS THAN (TO_DATE('2026-02-01','YYYY-MM-DD')),
    PARTITION ORDER_LOG_P202602 VALUES LESS THAN (TO_DATE('2026-03-01','YYYY-MM-DD')),
    PARTITION ORDER_LOG_P202603 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD')),
    PARTITION ORDER_LOG_P202604 VALUES LESS THAN (TO_DATE('2026-05-01','YYYY-MM-DD')),
    PARTITION ORDER_LOG_P202605 VALUES LESS THAN (TO_DATE('2026-06-01','YYYY-MM-DD')),
    PARTITION ORDER_LOG_PMAX    VALUES LESS THAN (MAXVALUE)
);

INSERT INTO system.ORDER_LOG (ORDER_ID, ORDER_DATE, CUSTOMER_ID, AMOUNT)
SELECT LEVEL, DATE '2026-01-01' + MOD(LEVEL, 150), MOD(LEVEL, 50) + 1, ROUND(DBMS_RANDOM.VALUE(1000, 500000), 2)
FROM DUAL CONNECT BY LEVEL <= 2000;

-- DAY granularity: daily API access log, last 10 days.
CREATE TABLE system.API_ACCESS_LOG
(
    LOG_ID      NUMBER NOT NULL,
    LOG_DATE    DATE NOT NULL,
    ENDPOINT    VARCHAR2(200),
    STATUS_CODE NUMBER
)
PARTITION BY RANGE (LOG_DATE)
(
    PARTITION API_ACCESS_LOG_P20260301 VALUES LESS THAN (TO_DATE('2026-03-02','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260302 VALUES LESS THAN (TO_DATE('2026-03-03','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260303 VALUES LESS THAN (TO_DATE('2026-03-04','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260304 VALUES LESS THAN (TO_DATE('2026-03-05','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260305 VALUES LESS THAN (TO_DATE('2026-03-06','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260306 VALUES LESS THAN (TO_DATE('2026-03-07','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260307 VALUES LESS THAN (TO_DATE('2026-03-08','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260308 VALUES LESS THAN (TO_DATE('2026-03-09','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260309 VALUES LESS THAN (TO_DATE('2026-03-10','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_P20260310 VALUES LESS THAN (TO_DATE('2026-03-11','YYYY-MM-DD')),
    PARTITION API_ACCESS_LOG_PMAX      VALUES LESS THAN (MAXVALUE)
);

INSERT INTO system.API_ACCESS_LOG (LOG_ID, LOG_DATE, ENDPOINT, STATUS_CODE)
SELECT LEVEL, DATE '2026-03-01' + MOD(LEVEL, 10), '/api/endpoint' || MOD(LEVEL, 10), CASE WHEN MOD(LEVEL, 20) = 0 THEN 500 ELSE 200 END
FROM DUAL CONNECT BY LEVEL <= 3000;

-- YEAR granularity: yearly settlement archive, 5 years.
CREATE TABLE system.YEARLY_SETTLEMENT
(
    SETTLEMENT_ID   NUMBER NOT NULL,
    SETTLE_DATE     DATE NOT NULL,
    BRANCH_CODE     VARCHAR2(10),
    TOTAL_AMOUNT    NUMBER(14,2)
)
PARTITION BY RANGE (SETTLE_DATE)
(
    PARTITION YEARLY_SETTLEMENT_P2022 VALUES LESS THAN (TO_DATE('2023-01-01','YYYY-MM-DD')),
    PARTITION YEARLY_SETTLEMENT_P2023 VALUES LESS THAN (TO_DATE('2024-01-01','YYYY-MM-DD')),
    PARTITION YEARLY_SETTLEMENT_P2024 VALUES LESS THAN (TO_DATE('2025-01-01','YYYY-MM-DD')),
    PARTITION YEARLY_SETTLEMENT_P2025 VALUES LESS THAN (TO_DATE('2026-01-01','YYYY-MM-DD')),
    PARTITION YEARLY_SETTLEMENT_P2026 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    PARTITION YEARLY_SETTLEMENT_PMAX  VALUES LESS THAN (MAXVALUE)
);

INSERT INTO system.YEARLY_SETTLEMENT (SETTLEMENT_ID, SETTLE_DATE, BRANCH_CODE, TOTAL_AMOUNT)
SELECT LEVEL, DATE '2022-01-01' + MOD(LEVEL, 1460), 'BR' || LPAD(MOD(LEVEL, 5) + 1, 2, '0'), ROUND(DBMS_RANDOM.VALUE(100000, 9000000), 2)
FROM DUAL CONNECT BY LEVEL <= 1500;

-- ILM registry rows describing the three sample tables above.
INSERT INTO pgdba.DEL_JOB_TABLE_LIST
  (TABLE_OWNER, TABLE_NAME, COMMENTS, WORK_GROUP, STD_COLUMN, START_HIGHVALUE, END_HIGHVALUE,
   DELETE_CYCLE, RANGE_TYPE, PARTITION_YN, PARTITION_TYPE, OGG_SYNC_YN, STATUS, LAST_DEL_JOB_TIME, STD_DATE, MEMO)
VALUES
  ('SYSTEM', 'ORDER_LOG', '주문 로그 - 월별 파티션 보관', 'BIZ', 'ORDER_DATE',
   'TO_DATE(''2026-01-01'',''YYYY-MM-DD'')', 'TO_DATE(''2026-06-01'',''YYYY-MM-DD'')',
   '6', 'MONTH', 'Y', 'RANGE', 'N', 'ACTIVE', SYSTIMESTAMP - 1, TO_CHAR(SYSDATE,'YYYYMMDD'), '6개월 보관 후 삭제');

INSERT INTO pgdba.DEL_JOB_TABLE_LIST
  (TABLE_OWNER, TABLE_NAME, COMMENTS, WORK_GROUP, STD_COLUMN, START_HIGHVALUE, END_HIGHVALUE,
   DELETE_CYCLE, RANGE_TYPE, PARTITION_YN, PARTITION_TYPE, OGG_SYNC_YN, STATUS, LAST_DEL_JOB_TIME, STD_DATE, MEMO)
VALUES
  ('SYSTEM', 'API_ACCESS_LOG', 'API 접근 로그 - 일별 파티션 보관', 'INF', 'LOG_DATE',
   'TO_DATE(''2026-03-01'',''YYYY-MM-DD'')', 'TO_DATE(''2026-03-11'',''YYYY-MM-DD'')',
   '10', 'DAY', 'Y', 'RANGE', 'N', 'ACTIVE', SYSTIMESTAMP - 2, TO_CHAR(SYSDATE,'YYYYMMDD'), '10일 보관 후 삭제');

INSERT INTO pgdba.DEL_JOB_TABLE_LIST
  (TABLE_OWNER, TABLE_NAME, COMMENTS, WORK_GROUP, STD_COLUMN, START_HIGHVALUE, END_HIGHVALUE,
   DELETE_CYCLE, RANGE_TYPE, PARTITION_YN, PARTITION_TYPE, OGG_SYNC_YN, STATUS, LAST_DEL_JOB_TIME, STD_DATE, MEMO)
VALUES
  ('SYSTEM', 'YEARLY_SETTLEMENT', '연간 정산 아카이브 - 연도별 파티션 보관', 'FIN', 'SETTLE_DATE',
   'TO_DATE(''2022-01-01'',''YYYY-MM-DD'')', 'TO_DATE(''2027-01-01'',''YYYY-MM-DD'')',
   '5', 'YEAR', 'Y', 'RANGE', 'Y', 'ACTIVE', SYSTIMESTAMP - 3, TO_CHAR(SYSDATE,'YYYYMMDD'), '5년 보관 후 삭제, OGG 동기화 대상');

COMMIT;
